CREATE TABLE IF NOT EXISTS `orders` (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    ISIN VARCHAR(12) NOT NULL,
    Amount INT NOT NULL,
    Price DECIMAL(10, 2) DEFAULT 0.00,
    State INT NOT NULL
);
